Output was colorized.

diff --git a/backup-sites b/backup-sites
--- a/backup-sites
+++ b/backup-sites
@@ -2,13 +2,13 @@
 
 BACKUP_PATH=${BACKUP_PATH=$HOME/sites-backups}
 BACKUP_COMMAND=$(dirname $(readlink -f $0))/joomla-backup
-echo $BACKUP_PATH
 
 current_time=$(date +%F_%R:%S)
 backup_dir=$BACKUP_PATH/$current_time
 
 mkdir $backup_dir
 if [[ $? -gt 0 ]]; then
+    echo "Can't create directory for backups ($backup_dir)"
     exit 1
 fi
 
@@ -19,8 +19,13 @@ for site in /etc/apache2/sites-available/*; do
     if [[ -z $site_name ]]; then
         echo "Backuping: $site"
     else
-        echo "Backuping: $site_name ($site)"
+        echo "Backuping: $(tput setaf 2)$site_name$(tput sgr 0) ($site)"
     fi
 
-    $BACKUP_COMMAND $site_path $backup_dir/$site_name\_$current_time.zip
+    backup_file=$backup_dir/$site_name\_$current_time.zip
+    $BACKUP_COMMAND $site_path $backup_file 0>/dev/null
+
+    if [[ $? -eq 0 ]]; then
+        echo "Backup saved to $backup_file"
+    fi
 done
diff --git a/joomla-backup b/joomla-backup
--- a/joomla-backup
+++ b/joomla-backup
@@ -11,17 +11,17 @@ PATH_TO_JOOMLA=$1
 BACKUP_FILE=$(readlink -f $2)
 
 if [[ ! -r $PATH_TO_JOOMLA ]]; then
-    echo "Error: Joomla directory not exists or not readable." 1>&2
+    echo "$(tput setaf 1)Error: Joomla directory not exists or not readable.$(tput sgr0)" 1>&2
     exit 1
 fi
 
 if [[ ! -r $PATH_TO_JOOMLA/configuration.php ]]; then
-    echo "Error: Joomla configuration file (configuration.php) not exits or not readable." 1>&2
+    echo "$(tput setaf 1)Error: Joomla configuration file (configuration.php) not exits or not readable.$(tput sgr0)" 1>&2
     exit 1
 fi
 
 if [[ ! -w $(dirname $BACKUP_FILE) ]]; then
-    echo "Error: directory with backup file not exits or not writable." 1>&2
+    echo "$(tput setaf 1)Error: directory with backup file not exits or not writable.$(tput sgr0)" 1>&2
     exit 1
 fi
 
