Updated.

diff --git a/backup-sites b/backup-sites
--- a/backup-sites
+++ b/backup-sites
@@ -1,33 +1,34 @@
 #!/usr/bin/env bash
 
-BACKUP_PATH=${BACKUP_PATH=$HOME/sites-backups}
-BACKUP_COMMAND=$(dirname $(readlink -f $0))/joomla-backup
+BACKUP_PATH=${BACKUP_PATH="$HOME/sites-backups"}
 
+current_path=$(dirname $(readlink -f $0))
 current_time=$(date +%F_%R:%S)
-backup_dir=$BACKUP_PATH/$current_time
+backup_dir="$BACKUP_PATH/$current_time"
 
-mkdir $backup_dir
-if [[ $? -gt 0 ]]; then
-    echo "Can't create directory for backups ($backup_dir)"
-    exit 1
-fi
+mkdir $backup_dir || (echo "Can't create directory for backups ($backup_dir)" 1>&2 && exit 1)
 
 for site in /etc/apache2/sites-available/*; do
     site_path=$(sed -ne 's/^[[:space:]]*DocumentRoot[[:space:]]\+\([^[:space:]]*\)/\1/p' $site) 
     site_name=$(sed -ne 's/^[[:space:]]*ServerName[[:space:]]\+\([^[:space:]]*\)/\1/p' $site) 
 
+    ([[ ! -d "$site_path" ]] || [[ -f "$site_path/.no-backup" ]]) && continue
+
     if [[ -z $site_name ]]; then
-        echo "Backuping: $site"
+        echo "Backing up: $site"
     else
-        echo "Backuping: $(tput setaf 2)$site_name$(tput sgr 0) ($site)"
+        echo "Backing up: $site_name ($site)"
     fi
     echo "Document root: $site_path"
 
     backup_file=$backup_dir/$site_name\_$current_time.zip
-    $BACKUP_COMMAND $site_path $backup_file 1>/dev/null
 
-    if [[ $? -eq 0 ]]; then
-        echo "Backup was saved to $backup_file"
+    if  [[ -f "$site_path/configuration.php" ]]; then
+        "$current_path/joomla-backup" $site_path $backup_file 1>/dev/null && \
+            echo "Ok. Backup was saved to $backup_file"
+    else
+        zip -ru $backup_file $site_path 1>/dev/null && \
+            echo "Ok. Backup was saved to $backup_file"
     fi
 
     echo 
